name: Build and deploy documentation

on:
  push:
    branches:
      - master
jobs:
  DeployDocumentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install poetry
      uses: dschep/install-poetry-action@v1.2
      with:
        version: 1.0.0b3
    - name: Install dependencies
      run: poetry install
    - name: Build documentation
      run: poetry run portray -- as_html --overwrite
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: site
