name: Build and deploy documentation

on:
  push:
    branches:
      - master
jobs:
  DeployDocumentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      uses: docker://abatilo/actions-poetry:3.7.4-stretch
      with:
        args: install

    - name: Build documentation
      uses: docker://abatilo/actions-poetry:3.7.4-stretch
      with:
        args: run portray as_html --overwrite

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: site
