name: Build and deploy documentation

on: [push]

jobs:
  DeployDocumentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2
      - name: Install dependencies
        run: poetry install
      - name: Build HTTP documentation
        run: npx redoc-cli bundle http-api.yml --output docs/http-api.html
      - name: Build documentation
        run: poetry run portray as_html --overwrite

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: site
        env:
          ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
        if: github.ref == 'refs/heads/master'
