name: Publish release to PyPI

on:
  release:
    types: [published]

jobs:
  publish_release_to_pypi:
    name: Build and publish a release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: "1.1.12"
      - name: Install dependencies
        run: poetry install
      - name: Update mkdocs config for local browsing
        run: sed -i "s/\[tool.portray.mkdocs\]$/&\nuse_directory_urls = false/" pyproject.toml
      - name: Build HTTP documentation
        run: npx redoc-cli bundle http-api.yml --output docs/http-api.html
      - name: Build documentation for publishing
        run: poetry run portray as_html --overwrite --output_dir blueye.sdk_docs
      - name: Build package with poetry, including documentation
        run: poetry build
      - name: Publish to PyPI
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
