name: Publish release to PyPI

on:
  release:
    types: [published]

jobs:
  publish_release_to_pypi:
    name: Build and publish a release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.2
        with:
          poetry-version: "2.0.1"
      - name: Install dependencies
        run: poetry install
      - name: Build HTTP documentation
        run:  npx @redocly/cli build-docs http-api.yml --output docs/http-api.html
      - name: Build documentation for publishing
        run: poetry run mkdocs build --no-directory-urls --site-dir blueye.sdk_docs
      - name: Build package with poetry, including documentation
        run: poetry build
      - name: Publish to PyPI
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
