name: Publish release to PyPI

on:
  release:
    types: [published]

jobs:
  publish_release_to_pypi:
    name: Build and publish a release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
         version: "0.7.11"
      - name: Build HTTP documentation
        run:  npx @redocly/cli build-docs http-api.yml --output docs/http-api.html
      - name: Build documentation for publishing
        run: uv run mkdocs build --no-directory-urls --site-dir blueye.sdk_docs
      - name: Build package (including documentation)
        run: uv build
      - name: Publish to PyPI
        run: uv publish --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/blueye_sdk-*
