name: Tests

on: [push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version:  ${{ matrix.python }}
    - name: Install poetry
      uses: dschep/install-poetry-action@v1.2
      with:
        version: 0.12.17
    - name: Install dependencies
      run: poetry install
    - name: Run tests
      run: poetry run pytest -k "not connected_to_drone" --cov-report=xml --cov blueye
    - name: Upload coverage
      run: curl -s https://codecov.io/bash | bash -s - -F $(echo ${{ matrix.os}} | cut -d "-" -f 1)
      shell: bash
      env:
        CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

  CheckFormatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: poetry install
      uses:  docker://abatilo/actions-poetry:3.7.4-stretch
      with:
        args: install
    - name: Check formatting
      uses: docker://abatilo/actions-poetry:3.7.4-stretch
      with:
        args: run black --check .
    - name: Print formatting diff
      uses: docker://abatilo/actions-poetry:3.7.4-stretch
      if: failure()
      with:
        args: run black --diff .
