name: Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: poetry install
      uses: docker://abatilo/actions-poetry:3.7.4-stretch
      with:
        args: install
    - name: Run pytest
      uses: docker://abatilo/actions-poetry:3.7.4-stretch
      with:
        args: "run pytest -k 'not connected_to_drone' tests"

  CheckFormatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: poetry install
      uses:  docker://abatilo/actions-poetry:3.7.4-stretch
      with:
        args: install
    - name: Check formatting
      uses: docker://abatilo/actions-poetry:3.7.4-stretch
      with:
        args: run black --check .
    - name: Print formatting diff
      uses: docker://abatilo/actions-poetry:3.7.4-stretch
      if: failure()
      with:
        args: run black --diff .
