name: Tests

on: [push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.10", "3.11", "3.12", "3.13"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
         version: "0.7.11"
      - name: Run tests
        run: uv run pytest -k "not connected_to_drone" --cov-report=xml --cov blueye
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          files: ./coverage.xml
          flags: ${{ matrix.os }}_${{ matrix.python }}
          name: codecov-umbrella
        continue-on-error: true

  CheckFormatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
         version: "0.7.11"
      - name: Check formatting
        run: uv run black --check .
      - name: Print formatting diff
        run: uv run black --diff .
        if: failure()
