name: Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: Blueye-Robotics/blueye.protocol
        path: blueye.sdk/blueye.protocol
        token: ${{ secrets.GIT_TOKEN }}
        ref: master
    - name: "Fix path to blueye.protocol"
      run: sed -i 's@../blueye.protocol/@blueye.protocol/@' pyproject.toml
    - uses: abatilo/actions-poetry@master
      with:
        args: install
    - uses: abatilo/actions-poetry@master
      with:
        args: "run pytest -k 'not connected_to_drone' tests"

  CheckFormatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: Blueye-Robotics/blueye.protocol
        path: blueye.sdk/blueye.protocol
        token: ${{ secrets.GIT_TOKEN }}
        ref: master
    - name: "Fix path to blueye.protocol"
      run: sed -i 's@../blueye.protocol/@blueye.protocol/@' pyproject.toml
    - uses: abatilo/actions-poetry@master
      with:
        args: install
    - uses: abatilo/actions-poetry@master
      with:
        args: run black --exclude blueye.protocol --check .
    - uses: abatilo/actions-poetry@master
      if: failure()
      with:
        args: run black --exclude blueye.protocol --diff .
